<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <EnablePackageValidation>false</EnablePackageValidation>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NJsonSchema" />
        <PackageReference Include="CommandLineParser" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Umbraco.Community.ContentAudit\Umbraco.Community.ContentAudit.csproj" />
    </ItemGroup>

</Project>
