//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.8.0+a486d5d
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>1902 SEO</summary>
	[PublishedModel("seoPackage1902")]
	public partial class SeoPackage1902 : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		public new const string ModelTypeAlias = "seoPackage1902";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<SeoPackage1902, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public SeoPackage1902(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Canonical Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("canonicalUrl1902Seo")]
		public virtual string CanonicalUrl1902Seo => this.Value<string>(_publishedValueFallback, "canonicalUrl1902Seo");

		///<summary>
		/// Clear Open Graph
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("clearOpenGraph1902Seo")]
		public virtual string ClearOpenGraph1902Seo => this.Value<string>(_publishedValueFallback, "clearOpenGraph1902Seo");

		///<summary>
		/// Description: You can write a short snippet or summary of the content of your page to tell your potential visitors what this page is about. This description will appear below the Page Title on search results (see Preview below). Your description can be any length, but keep in mind that search engines may truncate your description if it’s too long, so it’s best to keep it brief but comprehensive.   In some cases, Google may select a different part of your page’s content to show as the description on search results. This happens because of several possible reasons, such as: Google thinks that your meta description does not accurately describe the content of your page, or your meta description does not contain the keywords or terms that a person has searched for—in which case Google takes a part of your content that better matches the person’s search.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("description1902Seo")]
		public virtual string Description1902Seo => this.Value<string>(_publishedValueFallback, "description1902Seo");

		///<summary>
		/// Keyword: Keywords refer to the search terms that you want your page to appear or rank for in search results (e.g., if you want your page to be found when a person searches for “Umbraco package”, you can set “Umbraco package” as your keyword).  Keywords  are not limited to one - word terms; they can also be phrases that you think your target visitor would search for. These keywords are set up so 1902 SEO + can help you analyze your content and provide you suggestions on what you can improve based on the keywords you’ve chosen.They are not to be taken as a guarantee that your page will appear on search results when someone searches for your set keywords.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keyword1902Seo")]
		public virtual string Keyword1902Seo => this.Value<string>(_publishedValueFallback, "keyword1902Seo");

		///<summary>
		/// Schema
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ldScript1902Seo")]
		public virtual string LdScript1902Seo => this.Value<string>(_publishedValueFallback, "ldScript1902Seo");

		///<summary>
		/// Schema Business
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ldScriptBusiness1902Seo")]
		public virtual string LdScriptBusiness1902Seo => this.Value<string>(_publishedValueFallback, "ldScriptBusiness1902Seo");

		///<summary>
		/// 1902 Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("logo1902Seo")]
		public virtual string Logo1902Seo => this.Value<string>(_publishedValueFallback, "logo1902Seo");

		///<summary>
		/// No Follow: Check this box if you don’t want search engine crawlers to follow any outgoing links from this page. This means that you are not passing any “link juice” to the other sites or pages that you are linking to.  Link juice refers to the value that is passed from one site to another through hyperlinks.Basically, when you link to another site on your page(and that page is set to be followed), the search engines view the link as a vote or endorsement from your site that the page you are linking to is valuable.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("noFollow1902Seo")]
		public virtual string NoFollow1902Seo => this.Value<string>(_publishedValueFallback, "noFollow1902Seo");

		///<summary>
		/// No Index: Check this box if you don’t want this page to be indexed by search engines, that is, search engines will not include this particular page in search results.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("noIndex1902Seo")]
		public virtual string NoIndex1902Seo => this.Value<string>(_publishedValueFallback, "noIndex1902Seo");

		///<summary>
		/// Og Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogDescription1902Seo")]
		public virtual string OgDescription1902Seo => this.Value<string>(_publishedValueFallback, "ogDescription1902Seo");

		///<summary>
		/// Og Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogImage1902Seo")]
		public virtual string OgImage1902Seo => this.Value<string>(_publishedValueFallback, "ogImage1902Seo");

		///<summary>
		/// Open Graph Settings: When this page is shared on Facebook and other social media sites (except for Twitter), these will be the default content that will be displayed.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogTitle1902Seo")]
		public virtual string OgTitle1902Seo => this.Value<string>(_publishedValueFallback, "ogTitle1902Seo");

		///<summary>
		/// Og Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogType1902Seo")]
		public virtual string OgType1902Seo => this.Value<string>(_publishedValueFallback, "ogType1902Seo");

		///<summary>
		/// Open Graph: Open Graph lets you identify which elements from your page is displayed when it is shared on social media or similar sites. Usually, this includes a title, short description, and an image—all of which, when combined together, paint a visual representation of what your page is about. If you have set default values on the Global Open Graph settings on the SEO+ dashboard, those values will be automatically applied to this page as well. Here, you can override the default values and set up the specific open graph values for this page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openGraphCollapse1902Seo")]
		public virtual string OpenGraphCollapse1902Seo => this.Value<string>(_publishedValueFallback, "openGraphCollapse1902Seo");

		///<summary>
		/// Preview: This is how your page might look like when it appears on search results. Note that it might appear differently in certain cases, but generally, this is what you can expect your potential visitors to see when they see your page on search engines.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("preview1902Seo")]
		public virtual string Preview1902Seo => this.Value<string>(_publishedValueFallback, "preview1902Seo");

		///<summary>
		/// Site Map: A site map is a list of the URLs within your pages that you want to be indexed. This helps search engines crawl your site better and follow the links within your site easily.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteMapChangeFrequency1902seo")]
		public virtual string SiteMapChangeFrequency1902seo => this.Value<string>(_publishedValueFallback, "siteMapChangeFrequency1902seo");

		///<summary>
		/// Priority
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteMapPriority1902Seo")]
		public virtual string SiteMapPriority1902Seo => this.Value<string>(_publishedValueFallback, "siteMapPriority1902Seo");

		///<summary>
		/// Summary: This is a detailed review of your page in terms of SEO and performance. Click on “Expand” to view the complete analysis and recommendations. The most important issues to fix are in red, but also pay attention to the suggestions in yellow for further improvements on your SEO
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("summary1902Seo")]
		public virtual string Summary1902Seo => this.Value<string>(_publishedValueFallback, "summary1902Seo");

		///<summary>
		/// Title: This is the title for your page that appears as the clickable headline on search results.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title1902Seo")]
		public virtual string Title1902Seo => this.Value<string>(_publishedValueFallback, "title1902Seo");

		///<summary>
		/// Twitter Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterDescription1902Seo")]
		public virtual string TwitterDescription1902Seo => this.Value<string>(_publishedValueFallback, "twitterDescription1902Seo");

		///<summary>
		/// Twitter Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterImage1902Seo")]
		public virtual string TwitterImage1902Seo => this.Value<string>(_publishedValueFallback, "twitterImage1902Seo");

		///<summary>
		/// Twitter: When this page is shared on Twitter, these will be the default content that will be displayed.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.0+a486d5d")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterTitle1902Seo")]
		public virtual string TwitterTitle1902Seo => this.Value<string>(_publishedValueFallback, "twitterTitle1902Seo");
	}
}
