// This file is auto-generated by @hey-api/openapi-ts

export type AuditOverviewDto = {
    runDate?: string | null;
    totalPages?: number | null;
    totalPagesCrawled?: number | null;
    totalPagesBlocked?: number | null;
};

export type MediaTypeHeaderValue = {
    charSet?: string | null;
    readonly parameters: Array<(NameValueHeaderValue)>;
    mediaType?: string | null;
};

export type NameValueHeaderValue = {
    name: string;
    value?: string | null;
};

export type PageResourceDto = {
    url?: string | null;
    size?: number | null;
    statusCode: number;
    contentType?: MediaTypeHeaderValue | null;
};

export type PageResponseDto = {
    url?: string | null;
    size?: number | null;
    statusCode: number;
    contentType?: MediaTypeHeaderValue | null;
    pageTitle?: string | null;
    nodeKey?: string | null;
    resources: Array<(PageResourceDto)>;
};

export type GetLatestAuditOverviewResponse = AuditOverviewDto;

export type StartCrawlResponse = Array<(PageResponseDto)>;

export type $OpenApiTs = {
    '/umbraco/content-audit/api/v1/latest-audit': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: AuditOverviewDto;
            };
        };
    };
    '/umbraco/content-audit/api/v1/start-crawl': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<(PageResponseDto)>;
            };
        };
    };
};